name       : haskell-ghc-paths
version    : 0.1.0.9
release    : 2
source     :
    - http://hackage.haskell.org/package/ghc-paths-0.1.0.9/ghc-paths-0.1.0.9.tar.gz : afa68fb86123004c37c1dc354286af2d87a9dcfb12ddcb80e8bd0cd55bc87945
license    : BSD-3-Clause
component  : programming.haskell
summary    : Knowledge of GHC's installation directories
description: |
    Knowledge of GHC's installation directories
builddeps  :
    - ghc-dbginfo
    - ghc-devel
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
