name       : haskell-ghc-paths
version    : 0.1.0.12
release    : 3
source     :
    - https://hackage.haskell.org/package/ghc-paths-0.1.0.12/ghc-paths-0.1.0.12.tar.gz : 6ecbe676d073cb07989c61ce4c5709c4e67cbefdd2d55a4095f9388b6fe2c484
license    : BSD-3-Clause
component  : programming.haskell
summary    : Knowledge of GHC's installation directories
description: |
    Knowledge of GHC's installation directories
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
