name       : haskell-ghc-paths
version    : 0.1.0.9
release    : 1
source     :
    - http://hackage.haskell.org/package/ghc-paths-0.1.0.9/ghc-paths-0.1.0.9.tar.gz : afa68fb86123004c37c1dc354286af2d87a9dcfb12ddcb80e8bd0cd55bc87945
license    : BSD-3-Clause
component  : programming
summary    : Knowledge of GHC's installation directories
description: |
    Knowledge of GHC's installation directories 
builddeps  :
    - ghc
setup      : |
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 ghc-paths-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/ghc-paths-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/ghc-paths-$version/*.a
